version: "3.9"

services:
  postgres:
    image: postgres:14
    container_name: football_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: football
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: football_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:
